# codemagic.yaml
workflows:
  ios-app-build:
    name: Build SwByeDPI iOS App
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize submodules
        script: |
          git submodule update --init --recursive
      - name: "Remove corrupted xcodeproj to force SPM build"
        script: |
          rm -rf SwByeDPI.xcodeproj
          
      - name: Build and Archive iOS App (for Sideloading/Development)
        script: |
          # Change to the directory where the scheme is defined
          cd Example
          
          # Run the build command, adjusting archive path
          xcodebuild -scheme ByeByeDPI -destination 'generic/platform=iOS' -archivePath ../build/ByeDPI.xcarchive archive -verbose 
            CODE_SIGN_IDENTITY="-" 
            CODE_SIGNING_REQUIRED=NO 
            CODE_SIGN_ENTITLEMENTS=NO 
            DEVELOPMENT_TEAM="" 
            ENABLE_BITCODE=NO
            
      - name: Export IPA (for Sideloading/Development)
        script: |
          # The archive is in the root build folder
          xcodebuild -exportArchive -archivePath build/ByeDPI.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ipa

          # The exportOptions.plist should also be created at the root
          cat << EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
    artifacts:
      - build/ipa/*.ipa
